
// simplified renderer for the Instax catalog
function getLang(){ return localStorage.getItem('site-lang') || (navigator.language && navigator.language.startsWith('uz') ? 'uz' : (navigator.language && navigator.language.startsWith('en') ? 'en' : 'ru')); }
function setLang(l){ localStorage.setItem('site-lang', l); renderAll(); }
function formatPrice(v){ if(!v && v!==0) return ''; return v.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ' ') + ' UZS'; }

function renderFeatured(){ const cont=document.getElementById('featured-grid'); if(!cont) return; cont.innerHTML=''; const list=window.PRODUCTS.slice(0,6); const lang=getLang(); list.forEach(p=>{ const div=document.createElement('div'); div.className='product'; div.innerHTML = `<div class="image"><img src="${p.images[0]}" alt="${p.name.en}"></div><div style="font-weight:700;margin-top:6px">${p.name[lang]}</div><div style="color:var(--muted);font-size:14px">${p.desc[lang]}</div><div class="meta"><div class="price">${formatPrice(p.price)}</div><a class="btn" href="product.html?id=${p.id}">Подробнее</a></div>`; cont.appendChild(div); }); }

function renderProductsGrid(filterText='', category='all'){ const grid=document.getElementById('products-grid'); if(!grid) return; grid.innerHTML=''; const lang=getLang(); const list=window.PRODUCTS.filter(p=> (category==='all'||p.category===category) && (p.name[lang].toLowerCase().includes(filterText.toLowerCase())||p.desc[lang].toLowerCase().includes(filterText.toLowerCase())) ); if(list.length===0){ grid.innerHTML='<div style="grid-column:1/-1;color:var(--muted)">No products found</div>'; return; } list.forEach(p=>{ const el=document.createElement('div'); el.className='product'; el.innerHTML = `<div class="image">${p.images.map((im,idx)=>`<img src="${im}" style="width:100%;height:100%;object-fit:cover;display:${idx===0?'block':'none'}">`).join('')}</div><div style="display:flex;justify-content:space-between;align-items:center"><div style="font-weight:700">${p.name[lang]}</div></div><div style="color:var(--muted);font-size:14px">${p.desc[lang]}</div><div style="font-size:13px;color:var(--muted);margin-top:6px">${p.availability_note[getLang()]}</div><div class="meta"><div class="price">${formatPrice(p.price)}</div><div style="display:flex;gap:8px"><a class="btn" href="https://t.me/instax_uzbekistan?text=Здравствуйте!%20Хочу%20заказать%20${encodeURIComponent(p.name.ru)}" target="_blank">Заказать</a></div></div>`; grid.appendChild(el); }); attachProductCardHandlers(); }

function attachProductCardHandlers(){ document.querySelectorAll('.product').forEach(card=>{ const imgs=Array.from(card.querySelectorAll('.image img')); let hoverInterval; let idx=0; card.addEventListener('mouseenter', ()=>{ if(imgs.length<=1) return; hoverInterval=setInterval(()=>{ imgs.forEach(im=>im.style.display='none'); idx=(idx+1)%imgs.length; imgs[idx].style.display='block'; },900); }); card.addEventListener('mouseleave', ()=>{ clearInterval(hoverInterval); imgs.forEach((im,i)=> im.style.display = i===0 ? 'block' : 'none'); idx=0; }); }); }

function renderProductPage(){ const container=document.getElementById('product-container'); if(!container) return; const params=new URLSearchParams(location.search); const id=params.get('id'); const p=window.PRODUCTS.find(x=>x.id===id); if(!p){ container.innerHTML='<p>Product not found</p>'; return; } const lang=getLang(); container.innerHTML = `<div style="display:grid;grid-template-columns:420px 1fr;gap:20px;align-items:start"><div><div class="image" style="height:420px">${p.images.map((im,idx)=>`<img src="${im}" style="width:100%;height:100%;object-fit:cover;display:${idx===0?'block':'none'}">`).join('')}</div></div><div><h1 style="margin:0 0 8px">${p.name[lang]}</h1><div style="color:var(--muted);margin-bottom:10px">${p.sku}</div><div style="font-size:20px;font-weight:800;margin-bottom:8px">${formatPrice(p.price)}</div><div style="margin-bottom:12px">${p.desc[lang]}</div><div style="margin-bottom:8px;color:var(--muted)">${p.availability_note[getLang()]}</div><div style="display:flex;gap:8px;margin-bottom:12px"><a class="btn" href="https://t.me/instax_uzbekistan?text=Здравствуйте!%20Хочу%20заказать%20${encodeURIComponent(p.name.ru)}" target="_blank">Заказать</a></div></div></div>`; const imgs=container.querySelectorAll('.image img'); let idx=0; let iv; container.querySelector('.image')?.addEventListener('mouseenter', ()=>{ if(imgs.length<=1) return; iv=setInterval(()=>{ imgs[idx].style.display='none'; idx=(idx+1)%imgs.length; imgs[idx].style.display='block'; },900); }); container.querySelector('.image')?.addEventListener('mouseleave', ()=>{ clearInterval(iv); imgs.forEach((im,i)=> im.style.display = i===0 ? 'block' : 'none'); idx=0; }); }

function renderAll(){ renderFeatured(); renderProductsGrid(document.getElementById('search')?document.getElementById('search').value:'', document.getElementById('filter-cat')?document.getElementById('filter-cat').value:'all'); renderProductPage(); }

document.addEventListener('DOMContentLoaded', ()=>{ if(localStorage.getItem('site-theme')==='dark') document.body.classList.add('dark'); document.getElementById('themeToggle')?.addEventListener('click', ()=>{ document.body.classList.toggle('dark'); localStorage.setItem('site-theme', document.body.classList.contains('dark') ? 'dark' : 'light'); }); document.querySelectorAll('#langSwitcher').forEach(sel=>{ sel.value = localStorage.getItem('site-lang') || getLang(); sel.addEventListener('change', (e)=>{ localStorage.setItem('site-lang', e.target.value); renderAll(); }); }); document.getElementById('search')?.addEventListener('input',(e)=> renderProductsGrid(e.target.value, document.getElementById('filter-cat').value)); document.getElementById('filter-cat')?.addEventListener('change',(e)=> renderProductsGrid(document.getElementById('search')?document.getElementById('search').value:'', e.target.value)); renderAll(); });
